apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: secrets-sync
  namespace: argocd
spec:
  schedule: "*/1 * * * *"  # Run every minute
  timezone: "UTC"
  concurrencyPolicy: "Forbid"  # Don't run concurrent syncs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    entrypoint: sync-secrets
    serviceAccountName: workflow-executor
    templates:
    - name: sync-secrets
      steps:
      - - name: clone-and-sync
          template: clone-and-apply
    
    - name: clone-and-apply
      script:
        image: bitnami/kubectl:latest
        command: [bash]
        source: |
          #!/bin/bash
          set -e
          
          echo "========================================="
          echo "Starting Secrets Sync - $(date)"
          echo "========================================="
          
          # Clone the private repository
          echo "Cloning secrets repository (main branch)..."
          git clone -b main https://$(cat /etc/git-secret/username):$(cat /etc/git-secret/token)@github.com/dhruv-1001/amul-secrets-repo.git /tmp/secrets
          
          cd /tmp/secrets
          echo "-----------------------------------------"
          echo "Repo Info:"
          echo "Branch: $(git branch --show-current)"
          echo "Commit: $(git log -1 --oneline)"
          echo "-----------------------------------------"
          echo "Files in repo:"
          find . -maxdepth 3 -not -path '*/.*'
          echo "-----------------------------------------"
          
          # Function to check and apply secrets
          apply_if_changed() {
            local file=$1
            local namespace=$(grep "namespace:" "$file" | head -1 | awk '{print $2}')
            local name=$(grep "name:" "$file" | head -2 | tail -1 | awk '{print $2}')
            
            echo ""
            echo "Checking: $file"
            echo "  Namespace: $namespace"
            echo "  Secret: $name"
            
            # Check if namespace exists
            if ! kubectl get namespace "$namespace" > /dev/null 2>&1; then
              echo "  ⚠️  Namespace $namespace does not exist, skipping..."
              return
            fi
            
            # Check if secret exists
            if kubectl get secret "$name" -n "$namespace" > /dev/null 2>&1; then
              # Secret exists, check for differences
              echo "  Secret exists, checking for changes..."
              
              # Capture diff output but don't fail script if diff returns exit code 1 (which means diffs found)
              set +e
              kubectl diff -f "$file" > /dev/null 2>&1
              diff_exit_code=$?
              set -e
              
              if [ $diff_exit_code -eq 0 ]; then
                # Double check with dry-run because kubectl diff can sometimes be unreliable for deletions
                local dry_run_out=$(kubectl apply -f "$file" --dry-run=server 2>&1)
                
                if [[ "$dry_run_out" == *"configured"* ]]; then
                   echo "  ⚠️  Dry-run says 'configured' but diff said no changes. Applying to ensure consistency."
                   kubectl apply -f "$file"
                   echo "  ✓ Secret updated successfully"
                else
                   echo "  ✓ No changes detected"
                fi
              else
                echo "  ⚡ Changes detected. Applying..."
                kubectl apply -f "$file"
                echo "  ✓ Secret updated successfully"
              fi
            else
              # Secret doesn't exist, create it
              echo "  ⚡ Secret does not exist, creating..."
              kubectl apply -f "$file"
              echo "  ✓ Secret created successfully"
            fi
          }
          
          # Process YAML files in prod directory
          for env_dir in prod; do
            if [ -d "$env_dir" ]; then
              
              for secret_file in "$env_dir"/*.yaml; do
                if [ -f "$secret_file" ]; then
                  apply_if_changed "$secret_file"
                fi
              done
            fi
          done
          
          echo ""
          echo "========================================="
          echo "Secrets Sync Completed - $(date)"
          echo "========================================="
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
          readOnly: true
      volumes:
      - name: git-secret
        secret:
          secretName: git-credentials
