# Langfuse - LLM observability platform
# Depends on: external Postgres, Redis, ClickHouse, MinIO (see external-dbs/)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-config
  namespace: amul-prod
data:
  # Non-sensitive config - points to external DB host (vm2-db or similar)
  NEXTAUTH_URL: "https://langfuse.prod.amulai.in"
  TELEMETRY_ENABLED: "true"
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
  CLICKHOUSE_MIGRATION_URL: "clickhouse://10.5.25.36:9002/default"
  CLICKHOUSE_URL: "http://10.5.25.36:8123"
  CLICKHOUSE_CLUSTER_ENABLED: "false"
  LANGFUSE_USE_AZURE_BLOB: "false"
  LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_EVENT_UPLOAD_REGION: "auto"
  LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: "http://10.5.25.36:9000"
  LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_EVENT_UPLOAD_PREFIX: "events/"
  LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_MEDIA_UPLOAD_REGION: "auto"
  LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: "http://10.5.25.36:9000"
  LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: "media/"
  LANGFUSE_S3_BATCH_EXPORT_ENABLED: "false"
  LANGFUSE_S3_BATCH_EXPORT_BUCKET: "langfuse"
  LANGFUSE_S3_BATCH_EXPORT_PREFIX: "exports/"
  LANGFUSE_S3_BATCH_EXPORT_REGION: "auto"
  LANGFUSE_S3_BATCH_EXPORT_ENDPOINT: "http://10.5.25.36:9000"
  LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE: "true"
  REDIS_HOST: "10.5.25.36"
  REDIS_PORT: "6379"
  REDIS_TLS_ENABLED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-web
  namespace: amul-prod
  labels:
    app: langfuse-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse-web
  template:
    metadata:
      labels:
        app: langfuse-web
    spec:
      nodeSelector:
        role: backend
      initContainers:
        - name: create-bucket
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              for i in 1 2 3 4 5 6 7 8 9 10; do
                mc alias set minio http://10.5.25.36:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && break || sleep 5
              done
              mc mb minio/langfuse --ignore-existing || true
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: minio-access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: langfuse-secrets
                  key: minio-secret-key
      containers:
        - name: langfuse-web
          image: docker.io/langfuse/langfuse:3
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: langfuse-config
            - secretRef:
                name: langfuse-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /api/public/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/public/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-web
  namespace: amul-prod
spec:
  selector:
    app: langfuse-web
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-worker
  namespace: amul-prod
  labels:
    app: langfuse-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse-worker
  template:
    metadata:
      labels:
        app: langfuse-worker
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: langfuse-worker
          image: docker.io/langfuse/langfuse-worker:3
          ports:
            - containerPort: 3030
          envFrom:
            - configMapRef:
                name: langfuse-config
            - secretRef:
                name: langfuse-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-worker
  namespace: amul-prod
spec:
  selector:
    app: langfuse-worker
  ports:
    - port: 3030
      targetPort: 3030
