# OAN-UI Chat - frontend for amul-oan-api (chat BE)
# Built from OpenAgriNet/OAN-UI amul-prod branch
# VITE_API_BASE_URL baked at build: https://api.prod.amulai.in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oan-ui-chat
  namespace: amul-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oan-ui-chat
  template:
    metadata:
      labels:
        app: oan-ui-chat
    spec:
      nodeSelector:
        role: backend
      imagePullSecrets:
        - name: regcred
      containers:
        - name: oan-ui-chat
          image: dev-amulmitra.amul.com/oan-ui-chat:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: oan-ui-chat
  namespace: amul-prod
spec:
  selector:
    app: oan-ui-chat
  ports:
    - port: 8081
      targetPort: 8081
