# voice-oan-api (Voice OAN backend)
# Repo: https://github.com/OpenAgriNet/voice-oan-api (amul-prod branch)
# Depends on: redis (amul namespace). Uses Langfuse for observability.
# Supervisor runs uvicorn; AMUL_VOICE_UVICORN_WORKERS controls worker count.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-oan-api-config
  namespace: amul-prod
data:
  # Environment
  ENVIRONMENT: "production"
  # Redis - external (see external-dbs/)
  REDIS_HOST: "10.5.25.36"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # Marqo (vector search)
  MARQO_ENDPOINT_URL: "http://10.5.25.44:8882"
  MARQO_INDEX_NAME: "amul-veterinary-index"
  # LLM
  LLM_PROVIDER: "openai"
  LLM_MODEL_NAME: "gpt-5.1"
  # Langfuse (observability) - keys from secret
  LANGFUSE_BASE_URL: "https://langfuse.prod.amulai.in"
  LANGFUSE_TRACING_ENVIRONMENT: "voice-production"
  # Uvicorn workers - supervisor reads this for the fastapi program
  AMUL_VOICE_UVICORN_WORKERS: "4"
  NUDGE_TIMEOUT_SECONDS: "1.5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-oan-api
  namespace: amul-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-oan-api
  template:
    metadata:
      labels:
        app: voice-oan-api
    spec:
      nodeSelector:
        role: backend
      imagePullSecrets:
        - name: regcred
      containers:
        - name: voice-oan-api
          image: dev-amulmitra.amul.com/voice-oan-api:latest
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: voice-oan-api-config
            - secretRef:
                name: voice-oan-api-prod-secrets
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: voice-oan-api
  namespace: amul-prod
spec:
  selector:
    app: voice-oan-api
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
