# WorkflowTemplate for OAN-UI (Vite) builds - supports build args for VITE_* env
# Used for chat FE (amul-prod) and voice FE (amul-prod-voice)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-oan-ui
  namespace: argocd
spec:
  serviceAccountName: ci-builder
  entrypoint: build-and-push
  arguments:
    parameters:
      - name: repo_url
        value: "https://github.com/OpenAgriNet/OAN-UI.git"
      - name: branch
      - name: image_name
      - name: registry_url
      - name: vite_api_base_url
      - name: vite_voice_oan_mode
        value: ""

  templates:
  - name: build-and-push
    inputs:
      parameters:
        - name: repo_url
        - name: branch
        - name: image_name
        - name: registry_url
        - name: vite_api_base_url
        - name: vite_voice_oan_mode
        - name: target_namespace
        - name: target_deployment

    steps:
    - - name: get-git-info
        template: git-checkout-check
        arguments:
          parameters:
            - name: repo_url
              value: "{{inputs.parameters.repo_url}}"
            - name: branch
              value: "{{inputs.parameters.branch}}"
            - name: image_name
              value: "{{inputs.parameters.image_name}}"
            - name: registry_url
              value: "{{inputs.parameters.registry_url}}"
            - name: target_namespace
              value: "{{inputs.parameters.target_namespace}}"
            - name: target_deployment
              value: "{{inputs.parameters.target_deployment}}"

    - - name: build
        template: kaniko-build
        when: "{{steps.get-git-info.outputs.parameters.should_build}} == true"
        arguments:
          parameters:
            - name: repo_url
              value: "{{inputs.parameters.repo_url}}"
            - name: commit_hash
              value: "{{steps.get-git-info.outputs.parameters.commit_hash}}"
            - name: image_tag
              value: "{{steps.get-git-info.outputs.parameters.image_tag}}"
            - name: image_name
              value: "{{inputs.parameters.image_name}}"
            - name: registry_url
              value: "{{inputs.parameters.registry_url}}"
            - name: vite_api_base_url
              value: "{{inputs.parameters.vite_api_base_url}}"
            - name: vite_voice_oan_mode
              value: "{{inputs.parameters.vite_voice_oan_mode}}"

    - - name: deploy
        template: kubectl-deploy
        when: "{{steps.get-git-info.outputs.parameters.should_deploy}} == true"
        arguments:
          parameters:
            - name: namespace
              value: "{{inputs.parameters.target_namespace}}"
            - name: deployment
              value: "{{inputs.parameters.target_deployment}}"
            - name: container
              value: "{{inputs.parameters.image_name}}"
            - name: image
              value: "{{inputs.parameters.registry_url}}/{{inputs.parameters.image_name}}:{{steps.get-git-info.outputs.parameters.image_tag}}"

  - name: kubectl-deploy
    inputs:
      parameters:
        - name: namespace
        - name: deployment
        - name: container
        - name: image
    container:
      image: bitnami/kubectl:latest
      command: [sh, -c]
      args: ["kubectl set image deployment/{{inputs.parameters.deployment}} {{inputs.parameters.container}}={{inputs.parameters.image}} -n {{inputs.parameters.namespace}}"]

  - name: git-checkout-check
    inputs:
      parameters:
        - name: repo_url
        - name: branch
        - name: image_name
        - name: registry_url
        - name: target_namespace
        - name: target_deployment
    outputs:
      parameters:
        - name: should_build
          valueFrom:
            path: /tmp/should_build
        - name: commit_hash
          valueFrom:
            path: /tmp/commit_hash
        - name: image_tag
          valueFrom:
            path: /tmp/image_tag
        - name: should_deploy
          valueFrom:
            path: /tmp/should_deploy
    script:
      image: dtzar/helm-kubectl:latest
      command: [sh]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
      source: |
        REPO="{{inputs.parameters.repo_url}}"
        BRANCH="{{inputs.parameters.branch}}"
        REGISTRY="{{inputs.parameters.registry_url}}"
        IMAGE="{{inputs.parameters.image_name}}"
        LATEST_SHA=$(git ls-remote "$REPO" "refs/heads/$BRANCH" | awk '{print $1}' | cut -c1-7)
        if [ -z "$LATEST_SHA" ]; then echo "Branch $BRANCH not found"; exit 1; fi
        IMAGE_TAG="$BRANCH-$LATEST_SHA"
        echo "$LATEST_SHA" > /tmp/commit_hash
        echo "$IMAGE_TAG" > /tmp/image_tag
        CHECK_URL="http://$REGISTRY/v2/$IMAGE/manifests/$IMAGE_TAG"
        AUTH_HEADER=""
        if [ -f /kaniko/.docker/config.json ]; then
          AUTH_TOKEN=$(cat /kaniko/.docker/config.json | jq -r --arg reg "$REGISTRY" '.auths[$reg].auth // .auths["https://"+$reg].auth // empty')
          [ -n "$AUTH_TOKEN" ] && AUTH_HEADER="-H \"Authorization: Basic $AUTH_TOKEN\""
        fi
        HTTP_CODE=$(eval curl -L --location-trusted -k -s -o /dev/null -w "%{http_code}" $AUTH_HEADER -H \"Accept: application/vnd.docker.distribution.manifest.v2+json\" "$CHECK_URL" || echo "000")
        if [ "$HTTP_CODE" = "200" ]; then
          echo "false" > /tmp/should_build
          TARGET_NS="{{inputs.parameters.target_namespace}}"
          TARGET_DEPLOY="{{inputs.parameters.target_deployment}}"
          if [ -n "$TARGET_DEPLOY" ]; then
            CURRENT_IMAGE=$(kubectl get deployment -n "$TARGET_NS" "$TARGET_DEPLOY" -o jsonpath='{.spec.template.spec.containers[?(@.name=="'$IMAGE'")].image}' 2>/dev/null || echo "")
            EXPECTED_IMAGE="$REGISTRY/$IMAGE:$IMAGE_TAG"
            [ "$CURRENT_IMAGE" = "$EXPECTED_IMAGE" ] && echo "false" > /tmp/should_deploy || echo "true" > /tmp/should_deploy
          else
            echo "false" > /tmp/should_deploy
          fi
        else
          echo "true" > /tmp/should_build
          echo "true" > /tmp/should_deploy
        fi

  - name: kaniko-build
    inputs:
      parameters:
        - name: repo_url
        - name: commit_hash
        - name: image_tag
        - name: image_name
        - name: registry_url
        - name: vite_api_base_url
        - name: vite_voice_oan_mode
      artifacts:
        - name: source
          path: /src
          git:
            repo: "{{inputs.parameters.repo_url}}"
            revision: "{{inputs.parameters.commit_hash}}"
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--context=dir:///src"
        - "--dockerfile=/src/Dockerfile"
        - "--destination={{inputs.parameters.registry_url}}/{{inputs.parameters.image_name}}:{{inputs.parameters.image_tag}}"
        - "--build-arg=VITE_API_BASE_URL={{inputs.parameters.vite_api_base_url}}"
        - "--build-arg=VITE_VOICE_OAN_MODE={{inputs.parameters.vite_voice_oan_mode}}"
        - "--cache=true"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/

  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
