apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-exporter-config
  namespace: amul
data:
  nginxlog-exporter.hcl: |
    listen {
      port = 4040
      address = "0.0.0.0"
    }

    namespace "nginx" {
      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
      source {
        files = [
          "/mnt/nginx-logs/access.log"
        ]
      }
    }
