apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: amul-oan-api-uat-ci
  namespace: argocd
spec:
  schedule: "* * * * *"
  timezone: "Asia/Kolkata"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    serviceAccountName: ci-builder
    workflowTemplateRef:
      name: build-with-kaniko
    arguments:
      parameters:
        - name: repo_url
          value: "https://github.com/dhruv-1001/amul-oan-api.git"
        - name: branch
          value: "main"
        - name: image_name
          value: "amul-oan-api"
        - name: registry_url
          value: "dev-amulmitra.amul.com"
        - name: tag_strategy
          value: "branch"
        - name: target_namespace
          value: "amul-uat"
        - name: target_deployment
          value: "amul-oan-api"
