apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-log-exporter-config
  namespace: amul
data:
  nginxlog-exporter.hcl: |
    listen {
      port = 4040
      address = "0.0.0.0"
    }

    namespace "nginx" {
      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
      source {
        files = [
          "/mnt/nginx-logs/access.log"
        ]
      }
      
      # We attempt to match the standard format first since the sidecar 
      # might need the standard log format or a specifically tuned regex 
      # to parse our JSON. However, the exporter supports JSON directly 
      # if we tell it the format is JSON-lines, BUT the configuration is 
      # simpler if we just have Nginx ALSO output a standard log file 
      # for this exporter, or we configure the exporter to parse the JSON.
      # 
      # Given we are adding a file access_log, let's use the standard "combined" 
      # format for this file to make parsing trivial for the exporter, 
      # while keeping the JSON format for stdout/Loki.
    }
